// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Fallback to hardcoded URL for development if env var not loaded
const databaseUrl = process.env.DATABASE_URL || "postgresql://motico:motico_dev_pass@127.0.0.1:5433/motico_dev";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: databaseUrl,
  },
});
